package net.abi.abisEngine.rendering.shader.parser.fileTypes.yaml;

public class AEDemoProperty {
	String AE_DEMO_PROPERTY_IDENTIFIER;
	String[] AE_DEMO_PROPERTY_PARAMETERS;

	public AEDemoProperty() {
	}

	public String getAE_DEMO_PROPERTY_IDENTIFIER() {
		return AE_DEMO_PROPERTY_IDENTIFIER;
	}

	public void setAE_DEMO_PROPERTY_IDENTIFIER(String aE_DEMO_PROPERTY_IDENTIFIER) {
		AE_DEMO_PROPERTY_IDENTIFIER = aE_DEMO_PROPERTY_IDENTIFIER;
	}

	public String[] getAE_DEMO_PROPERTY_PARAMETERS() {
		return AE_DEMO_PROPERTY_PARAMETERS;
	}

	public void setAE_DEMO_PROPERTY_PARAMETERS(String[] aE_DEMO_PROPERTY_PARAMETERS) {
		AE_DEMO_PROPERTY_PARAMETERS = aE_DEMO_PROPERTY_PARAMETERS;
	}

}
