package net.abi.abisEngine.rendering.shader.parser.fileTypes.yaml;

public class AEPrepProperty {
	String AE_PREP_PROPERTY_IDENTIFIER;
	String[] AE_PREP_PROPERTY_PARAMETERS;

	public AEPrepProperty() {
	}

	public String getAE_PREP_PROPERTY_IDENTIFIER() {
		return AE_PREP_PROPERTY_IDENTIFIER;
	}

	public void setAE_PREP_PROPERTY_IDENTIFIER(String aE_PREP_PROPERTY_IDENTIFIER) {
		AE_PREP_PROPERTY_IDENTIFIER = aE_PREP_PROPERTY_IDENTIFIER;
	}

	public String[] getAE_PREP_PROPERTY_PARAMETERS() {
		return AE_PREP_PROPERTY_PARAMETERS;
	}

	public void setAE_PREP_PROPERTY_PARAMETERS(String[] aE_PREP_PROPERTY_PARAMETERS) {
		AE_PREP_PROPERTY_PARAMETERS = aE_PREP_PROPERTY_PARAMETERS;
	}
}
